export const LocalStorageKeys = {
  FREEDOM_ACCESS_TOKEN: 'FREEDOM_ACCESS_TOKEN',
  FREEDOM_REFRESH_TOKEN: 'FREEDOM_REFRESH_TOKEN',
  ACTIVE_SIDEBAR_BUTTON: 'ACTIVE_SIDEBAR_BUTTON',
  ANSWER_FROM_DATA: 'ANSWER_FROM_DATA',
};
